### PR TITLE
chore(project): improved project baseline for Gradle, Java tooling, SDK and deprecations

### PR DESCRIPTION
**Pull request by holgerstolzenberg**
# Description

I received reports from my team that Spring Boot 4(.1) compatibility is still not given even after the latest release.
I do not have the full details yet but thought I'd take an initial investigation.

For the investigation, I increased the Spring Boot baseline locally temporarily to identify some issues, that have now been fixed with this PR.

The PR also brings some quality of life improvements to the Java/Gradle ecosystem and should be treated as a mandatory step before tackling other incompatibility issues.

A problem found the PR does not address so far is a change in the `testcontainers` dependency coordinates that is breaking with the 4.1 baseline.

# What changes are made to solve it?

- upgrade to latest Gradle and adoption of build config
- use Java toolchain config for Gradle
- cleanup of main Gradle script
- do not rely on Spring Boots `PropertyMapper` as it is internal API
- upgrade to the latest OpenFGA SDK
- fix spotless deprecations
- fix potential upcoming deprecation for `ObjectMapper` config
- added SDKMan rc file
- update the Gradle baseline of the example
- rely on Spring Boots JSON starter

# References
- none yet, I will open a issue for tracking on next working day

# Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

## Summary by CodeRabbit

* **New Features**
  * Added support for Java 17 through the project toolchain.
  * Updated the OpenFGA SDK to version 0.9.9.

* **Bug Fixes**
  * Improved application configuration handling for credentials, timeouts, headers, telemetry, and other client settings.
  * Ensured null-valued properties are omitted from JSON output.
  * Retained validation for incomplete client-credentials configuration.

* **Chores**
  * Upgraded Gradle and build plugins.
  * Improved Gradle wrapper compatibility and test reporting.
  * Updated the configured Java runtime to `17.0.20-librca`.

### CODE REVIEW

File: gradlew.bat [hunk 1]
```diff
@@ -51,7 +51,7 @@ echo. 1>&2
 echo Please set the JAVA_HOME variable in your environment to match the 1>&2
 echo location of your Java installation. 1>&2
 
-goto fail
+"%COMSPEC%" /c exit 1
```
[the remark this answers is not in the document]
Comment (holgerstolzenberg) [reply gradlew.bat:54]: File is coming from the Gradle wrapper distribution, will not change it.

File: src/test/java/dev/openfga/autoconfigure/OpenFgaAutoConfigurationTests.java [hunk 2]
```diff
@@ -75,7 +76,7 @@ void connectionDetailsBeanActivatesBeansAndSuppliesApiUrl() {
                 .withConfiguration(AutoConfigurations.of(OpenFgaAutoConfiguration.class))
                 .run(context -> {
                     assertThat(context.containsBean("fgaClient"), is(true));
-                    ClientConfiguration config = (ClientConfiguration) context.getBean("fgaConfig");
+                    BaseConfiguration config = (ClientConfiguration) context.getBean("fgaConfig");
```
[the remark this answers is not in the document]
Comment (holgerstolzenberg) [reply src/test/java/dev/openfga/autoconfigure/OpenFgaAutoConfigurationTests.java]: Fixed with [722943f](https://github.com/openfga/spring-boot-starter/pull/183/commits/722943f135cd2f443e0aa1169fa9dce832f51b93)

**Comment by Adrastopoulos** [comment]
This is a good start, I have a few nitpicks: 

- there is quite a bit of stylistic test churn (`ClientConfiguration x` -> `final var x`). Can we justify these changes? the `BaseConfiguration` ones also look unintentional with some test casts to `BaseConfiguration` and others casting to `ClientConfiguration`. 
 - PropertyMapper is not an internal api. it's appropriately used for mapping @ConfigurationProperties ([docs](https://docs.spring.io/spring-boot/api/java/org/springframework/boot/context/properties/PropertyMapper.html)). See [kafka](https://github.com/spring-projects/spring-boot/blob/v4.1.0/module/spring-boot-kafka/src/main/java/org/springframework/boot/kafka/autoconfigure/ConcurrentKafkaListenerContainerFactoryConfigurer.java#L215-L255), grpc client config, flyway, actuator, spring ai's starters.
 - The problem is that `Source.as()` was re-signatured in SB 4.0 so a starter compiled against 3.x fails on 4.x with:
   ```
     NoSuchMethodError: PropertyMapper$Source.as(java.util.function.Function)
   ```
   which applies only to the 2 `.as()` call sites (`toCredentials`, `toTelemetryConfiguration`). So the fix in my opinion is to keep `PropertyMapper` and move the conversion into the lambda:
   ```java
     map.from(openFgaProperties::getCredentials)
        .to(c -> clientConfiguration.credentials(toCredentials(c)));
   ```
   Also, `PropertyMapper` filters nulls by default so we don't need the `.when(Objects::nonNull)`.
 - CI only builds the 3.4 baseline. We need add a Boot 4 BOM row to the matrix.
 - spring-boot-starter-json should not be added as an implementation dep. it pulls in spring-web. Instead, this would suffice:
   ```gradle
     implementation 'com.fasterxml.jackson.core:jackson-databind'
     implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
   ```
- `jacksonDatabindNullableVersion=0.2.6` is now an implementation dep but sdk `0.9.9` wants `0.2.10`. resolves to `0.2.10` anyway, so the pin is just misleading now.
- the pinned 17 toolchain means the java: [21] matrix row runs on 17.
- examples/servlet wrapper was never regenerated, still on `8.14.5`, and didn't get the `distributionSha256Sum` the root did.
- `id 'java'` -> `id 'java-library'` in the example seems wrong for an app module.
- the `dependencyManagement { imports { mavenBom ... } }` block in the example is a no-op, the boot plugin already imports it.
- `id 'wrapper'` is redundant, the wrapper task is there on the root project regardless.

**Comment by holgerstolzenberg** [comment]
So I try to disect the latest comment a bit:

---

> there is quite a bit of stylistic test churn (ClientConfiguration x -> final var x). Can we justify these changes? 

- I reverted the inconsitent use of `final`, my IDE is just a bit more picky about that

---

> the BaseConfiguration ones also look unintentional with some test casts to BaseConfiguration and others casting to ClientConfiguration.

- this changes have been remarks of the automated code review, please see resolved comments above
- so they have been intentional
- I think they are legit, the one test only tests on base properties/methods

---

> PropertyMapper is not an internal api. it's appropriately used for mapping @ConfigurationProperties (docs). See kafka, grpc client config, flyway, actuator, spring ai's starters.

By internal I meant something from the framework, never used it before. Yet, the Javadoc states, it is exactly for that purpose.
I can revert that change if wanted and apply the suggested fix.

To me the question is, is it that valuable. Sure, the DSL looks nicer, yet you still rely on Spring Boot API that might change.

@SoulPancake - do want that changed?

---

> CI only builds the 3.4 baseline. We need add a Boot 4 BOM row to the matrix.

Not sure if we should tackle this with ticket. At fist, the question needs to be clarified if such a matrix baseline is wanted. I would like the ticket as scoped as possible to get "quick help" for guys needing the starter compatible with SB-4 in the first place.

Also, if you do that, managing the Jackson dependencies will become a bit more tricky, as the coordinates changed.
So that contradicts a bit more with the below statement in regards of the spring-boot-json-starter dependency.

---

> spring-boot-starter-json should not be added as an implementation dep. it pulls in spring-web.

I tend to say that is a bit odd, but after double checking the dependency tree:

- you are right 😀
- `spring-web` gets also pulled in transitively by `spring-boot-starter-security` already
- so I think the starter was never designed around a non web stack application - so far
- it might help with change of jackson dependency coordinates for the SB-4 baseline
- I'd leave it to the maintainers to decide upon this one

@SoulPancake - should we revert to plain Jackson dependencies?

---

> jacksonDatabindNullableVersion=0.2.6 is now an implementation dep but sdk 0.9.9 wants 0.2.10. resolves to 0.2.10 anyway, so the pin is just misleading now.

- updated the dependency to `0.2.10`

---

> the pinned 17 toolchain means the java: [21] matrix row runs on 17.

- isn't that exactly how it should be?
- the final artifact published is compiled with 17 target, but by which JVM is used for the actual publication step?
- should a 21 JVM not also compile to a 17 target?

@Adrastopoulos  - please elaborate a bit more how you would change that?

---

> examples/servlet wrapper was never regenerated, still on 8.14.5, and didn't get the distributionSha256Sum the root did.

- fixed

---

> the dependencyManagement { imports { mavenBom ... } } block in the example is a no-op, the boot plugin already imports it.

Thats new to me, but TBH, a little less magic, being a bit more explicit, helps, especially people new to the ecosystem.
So I'd like to keep it.

---

> id 'wrapper' is redundant, the wrapper task is there on the root project regardless.

- same, I'd like to keep it a bit more explicit

**Comment by holgerstolzenberg** [comment]
@SoulPancake, @Adrastopoulos 

So to sum up, it boils down to the following aspects to clarify:

- should we use PropertyMapper API
- should we use the the json starter or plain jackson deps
- how to continue with the Java toolchain and the matrix builds

Maybe its an option to inject the Java version as property also, defaulting to `17` and adopting the property to be set by the matrix builds in the CI!?

**Comment by holgerstolzenberg** [comment]
@SoulPancake I am not able to see the Snyk failure. Maybe you can post the failing policy/test here, so that we can address.

**Comment by Adrastopoulos** [comment]
> To me the question is, is it that valuable. Sure, the DSL looks nicer, yet you still rely on Spring Boot API that might change.

I think so. It's used across a lot of starters similar to this one. Regardless, dropping it doesn't actually fix the bug.

> should we revert to plain Jackson dependencies?

Yeah, and it actually cuts against the SB4 goal rather than helping it. In 3.4 `spring-boot-starter-json` pulls `com.fasterxml.jackson.core:jackson-databind`, but in 4.0 it resolves via `spring-boot-jackson` to `tools.jackson.core:jackson-databind:3.x`. So under a Boot 4 BOM you'd get Jackson 3 on the classpath while the SDK and `jackson-databind-nullable` still need Jackson 2. Explicit `com.fasterxml` coordinates work on both baselines.

> isn't that exactly how it should be? [...] should a 21 JVM not also compile to a 17 target?

Yes, the target is fine. The issue is with the matrix. Before this, the `java: 21` row ran the tests on JDK 21. Now Gradle uses 17 no matter what `setup-java` installed, so the 17 and 21 rows run the same thing.

> Maybe its an option to inject the Java version as property also, defaulting to 17

Yeah, that could work.

> CI only builds the 3.4 baseline...Not sure if we should tackle this with ticket.

Agreed

**Comment by curfew-marathon** [comment]
#183 is the first piece of a larger Jackson 2 to 3 migration that runs through `sdk-generator`, `java-sdk`, and this starter. I wrote it up as an RFC so we can get a holistic solution to the whole problem rather than solving it piece by piece: https://github.com/openfga/rfcs/pull/36

The three things still open in this thread all have an answer in there. Pulling them out so we're not deciding them twice:

**Jackson deps.** I'd keep the explicit `com.fasterxml` coordinates instead of leaning on `spring-boot-starter-json`. Under a Boot 4 BOM that starter pulls `tools.jackson.core:jackson-databind:3.x`, which fights the SDK and `jackson-databind-nullable` (both still on Jackson 2). The explicit coordinates work on both baselines. @Adrastopoulos already called this out above.

**PropertyMapper.** Keep it. As @Adrastopoulos worked out above, the only real problem is `Source.as(Function)` getting re-signatured in SB 4.0, and that only hits the two `.as()` sites (`toCredentials`, `toTelemetryConfiguration`). His fix (moving the conversion into the `.to(...)` lambda) handles it without the wider test churn.

**Toolchain and CI.** A Boot 4 BOM row would help, and a ticket for it is fine. @Adrastopoulos also spotted that after the toolchain change the `17` and `21` rows both build on 17, so they run the same thing right now.

On scope: I'd keep this PR as a clean 3.4 baseline that doesn't work against SB4. The actual SB4 support (the dual `@ConditionalOnClass` setup that hands the SDK a `JsonSerializer`) is a later wave in the RFC, gated on the Jackson 3 SDK major. This PR is what that wave builds on, so it's exactly the right place to start.

@holgerstolzenberg @Adrastopoulos @SoulPancake does this match how you're seeing it? If so, a thumbs-up or a quick note on the RFC keeps it all in one place, and I'll fold in whatever we land on here.

**Comment by holgerstolzenberg** [comment]
@curfew-marathon Good summary, will make the necessary changes tomorrow.

**Comment by holgerstolzenberg** [comment]
@curfew-marathon, @SoulPancake, @Adrastopoulos

# ✅ Jackson
Reverted to usage of explicit dependency declarations

# ✅ PropertyMapper
Reverted to using Spring property mapper, but fixed the issue with the mapping methods. Kept `.when(Objects::nonNull)` as without, on SB 3 it fails the tests, also its more consistent then.

# ❓ JDK-17 baseline and toolchain
I am thinking back and force and it feels like I have never done that before, but I still think we are fine:
- the starter defines JDK-17 as it baseline
- that means, as a consumer, I can run the starter with every JDK ≥17
- therefore the starter needs to be compile **and packaged/published** with `17` as `targetCompatibility` which is done by the toolchain by now
- the starter currently gets distributed as *one* maven dependency, targeted at `17`, which is fine
- the Github action build runs a matrix for `17` and `21`
- this just confirms the starter can be compiled by a `21` compiler towards `17`, just confirming future upgrade paths

So nothing to do on that front I think - or if I am mistaken, can someone then please open a follow up ticket and describe it properly!? Merci.

So IMHO, this one is ready for final review + merge.

✌️

**Review by SoulPancake — CHANGES_REQUESTED** [review]
It still seems to crash on Boot 4.0.7:

```
NoSuchMethodError: 'PropertyMapper$Source PropertyMapper$Source.as(java.util.function.Function)'
  at dev.openfga.autoconfigure.OpenFgaAutoConfiguration.fgaConfig(OpenFgaAutoConfiguration.java:88)
```

503e1b6 only fixed the credentials site, line 88 still has the telemetry `.as()`. And the chain runs it even with no telemetry configured, so this breaks every SB4 app. Needs the same treatment:

```java
map.from(openFgaProperties::getTelemetryConfiguration)
        .when(Objects::nonNull)
        .to(t -> clientConfiguration.telemetryConfiguration(toTelemetryConfiguration(t)));
```

I tried that locally and it works on both 3.4.13 and 4.0.7. Keeping `.when(Objects::nonNull)` makes sense since 3.4's `to()` doesn't null-check and 4.0 dropped `whenNonNull()`.

Also the 0.2.10 nullable pin now downgrades the 0.2.11 that sdk 0.9.11 brings in, and that goes into the published pom. Should be 0.2.11.

**Comment by holgerstolzenberg** [comment]
@SoulPancake Done.

**Comment by SoulPancake** [comment]
Thanks a lot @holgerstolzenberg

**Review by SoulPancake — APPROVED** [review]
LGTM

**Comment by holgerstolzenberg** [comment]
@SoulPancake Good :-). Lets merge then...
